// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzsgmplevvyeromzvcjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16c2dtcGxldnZ5ZXJvbXp2Y2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODQ4OTYsImV4cCI6MjA2MTY2MDg5Nn0.krX9VBqcizNzHFIOia7EXPmxCNrLSwTPz3PnDYpgShI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
